name: Go Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
    unittest:
      name: Unitest Test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Go 1.21.8
          uses: actions/setup-go@v4
          with:
            go-version: 1.21.8
        - name: Run unittest
          run: go test -v  ./... 
    quality-check:
      name: Quality Scan
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: sonarsource/sonarqube-scan-action@master
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        # If you wish to fail your job when the Quality Gate is red, uncomment the
        # following lines. This would typically be used to fail a deployment.
        - uses: sonarsource/sonarqube-quality-gate-action@master
          timeout-minutes: 5
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

